name: Deploy forum to digital ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_FORUM_HOST }}
          port: 22
          username: ${{ secrets.SSH_FORUM_USERNAME }}
          key: ${{ secrets.SSH_FORUM_KEY }}
          script: |
            cd Forumm
            echo "Deploying to production server..."
            git reset --hard HEAD 
            git pull
            composer install
            php artisan migrate:refresh --seed
            php artisan reset_cache_Key
            npm install
            npm run build
            php artisan inertia:stop-ssr
            echo "Deployed to production server!"

            
