name: Deploy forum to digital ocean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_FORUM_HOST }}
          port: 22
          username: ${{ secrets.SSH_FORUM_USERNAME }}
          key: ${{ secrets.SSH_FORUM_KEY }}
          script: |
            cd Forumm
            git pull
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            npm install
            npm run build
            php artisan inertia:stop-ssr
            # Temporarily remove caching commands
            # php artisan cache:clear
            # php artisan config:cache
            # php artisan route:cache
            # php artisan view:cache
            
